"""Create an allowlisted, dependency-free transfer archive and verify extraction."""
import argparse
import io
import json
import tarfile
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from verify_transfer import sha256, verify_package

ROOT = Path(__file__).resolve().parents[1]


def package_files(root: Path) -> list[Path]:
    files = [root / name for name in ("README.md", ".gitignore", "pyproject.toml", "count_params.py")]
    for directory in ("src", "scripts", "configs", "requirements", "tests", "docs"):
        files.extend(path for path in (root / directory).rglob("*")
                     if path.is_file() and path.suffix in (".py", ".yaml", ".md", ".json", ".xml", ".in", ".lock", ".sh", ".txt"))
    files.extend(root / "artifacts/cp2" / name for name in
                 ("tokenizer.json", "tokenizer_training.json", "manifest.json", "source_card.md"))
    files.extend(root / "artifacts/cp3_data" / name for name in
                 ("manifest.json", "train.bin", "validation.bin", "train.index.jsonl", "validation.index.jsonl"))
    # The report generated by this build must not enter its own archive.
    return sorted(set(path for path in files if path != root / "docs/results/runpod_package.json"))


def build_package(root: Path, destination: Path) -> dict[str, Any]:
    if destination.exists():
        raise FileExistsError(f"Preserving existing package: {destination}")
    destination.mkdir(parents=True)
    paths = package_files(root)
    manifest = {"format_version": 1, "created_utc": datetime.now(timezone.utc).isoformat(),
                "python": "3.12.13", "uv": "0.11.28", "platform": "Linux x86_64",
                "torch": "2.8.0+cu128", "files": {}}
    for path in paths:
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"Missing/unsafe package file: {path}")
        manifest["files"][path.relative_to(root).as_posix()] = {"bytes": path.stat().st_size, "sha256": sha256(path)}
    archive = destination / "helixdepth-runpod.tar.gz"
    with tarfile.open(archive, "w:gz") as output:
        for path in paths:
            output.add(path, arcname=path.relative_to(root).as_posix(), recursive=False)
        encoded = (json.dumps(manifest, indent=2) + "\n").encode()
        metadata = tarfile.TarInfo("transfer_manifest.json")
        metadata.size = len(encoded)
        output.addfile(metadata, io.BytesIO(encoded))
    checksum = sha256(archive)
    (destination / f"{archive.name}.sha256").write_text(f"{checksum}  {archive.name}\n", encoding="utf-8")
    with tempfile.TemporaryDirectory(dir=destination) as temporary:
        extracted = Path(temporary)
        with tarfile.open(archive, "r:gz") as source:
            source.extractall(extracted, filter="data")
        verification = verify_package(extracted)
    return {"archive": str(archive), "archive_bytes": archive.stat().st_size,
            "archive_sha256": checksum, "dependency_lock_sha256": sha256(root / "requirements/runpod.lock"),
            "round_trip_verification": verification, "files": manifest["files"],
            "gpu_measurements": "Not executed: local CPU-only environment", "main_training_started": False}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "artifacts/runpod_ready")
    args = parser.parse_args()
    report = build_package(ROOT, args.output)
    (ROOT / "docs/results/runpod_package.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in report.items() if key != "files"}, indent=2))


if __name__ == "__main__":
    main()
